server:
  port: 8081
spring:
  redis:
    host: 127.0.0.1
  datasource:
    url: jdbc:mysql://localhost:3306/miaosha?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: root
mybatis:
  mapper-locations: mapper/**/*.xml